name: golang-pipeline
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.22
    steps:
      - uses: actions/checkout@v4

      - name: Run Unix Tests
        run: GOOS=linus GOARCH=amd64 go test

      - name: Vet
        run: |
          go vet ./...